version: "3.3"
services:
  db1:
    image: stellar/stellar-core-state
    volumes: ["db1-data:/var/lib/postgresql/data", "db1-unixsocket:/postgresql-unix-sockets"]
  db2:
    image: stellar/stellar-core-state
    volumes: ["db2-data:/var/lib/postgresql/data", "db2-unixsocket:/postgresql-unix-sockets"]
  db3:
    image: stellar/stellar-core-state
    volumes: ["db3-data:/var/lib/postgresql/data", "db3-unixsocket:/postgresql-unix-sockets"]
  db4:
    image: stellar/stellar-core-state
    volumes: ["db4-data:/var/lib/postgresql/data", "db4-unixsocket:/postgresql-unix-sockets"]

  core1:
    image: zzim2x/stellar-core-quorum:9.2.0
    env_file: ["core.env"]
    command: "core1 initdb forcescp"
    volumes: ["db1-unixsocket:/var/run/postgres"]
    environment:
      KNOWN_PEERS: '["core2", "core3", "core4"]'
    ports:
      - "11681:11626"
    depends_on: ["db1"]
  core2:
    image: zzim2x/stellar-core-quorum:9.2.0
    env_file: ["core.env"]
    command: "core2 initdb forcescp"
    volumes: ["db2-unixsocket:/var/run/postgres"]
    environment:
      KNOWN_PEERS: '["core1", "core3", "core4"]'
    ports:
      - "11682:11626"
    depends_on: ["db2"]
  core3:
    image: zzim2x/stellar-core-quorum:9.2.0
    env_file: ["core.env"]
    command: "core3 initdb forcescp"
    volumes: ["db3-unixsocket:/var/run/postgres"]
    environment:
      KNOWN_PEERS: '["core1", "core2", "core4"]'
    ports:
      - "11683:11626"
    depends_on: ["db3"]
  core4:
    image: zzim2x/stellar-core-quorum:9.2.0
    env_file: ["core.env"]
    command: "core4 initdb forcescp"
    volumes: ["db4-unixsocket:/var/run/postgres"]
    environment:
      KNOWN_PEERS: '["core1", "core2", "core3"]'
    ports:
      - "11684:11626"
    depends_on: ["db4"]
volumes:
  db1-data:
  db1-unixsocket:
  db2-data:
  db2-unixsocket:
  db3-data:
  db3-unixsocket:
  db4-data:
  db4-unixsocket: